---
title: "Data Processing for MS in Urban Analytics Capstone"
date: "2024-7-18"
author: "Helena Lindsay"
output: 
  html_document:
    theme: "cosmo"
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message=FALSE, warning=FALSE, echo=FALSE}
# Package names
packages <- c("RedditExtractoR", "anytime", "magrittr", "ggplot2", "dplyr", "tidytext", "tidyverse", "igraph", "ggraph", "tidyr", "wordcloud2", "textdata", "sf", "tmap", "patchwork", "stringr", "glue", "stringi", "tibble", "readxl")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
install.packages(packages[!installed_packages])
}

# Load packages
invisible(lapply(packages, library, character.only = TRUE))
```



## Regression {.tabset}

### Transit Agency data (VOMS)
```{r, message=FALSE, warning=FALSE, echo=FALSE}
Agencies <- read.csv("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Service.csv")

Agencies <- Agencies[order(Agencies$Service.Area.Population, decreasing = TRUE), ]
Agencies <- Agencies %>%
  filter(Type.Of.Service == 'DO') %>%
  filter(Mode %in% c('HR', 'MB')) %>%
  filter(Time.Period == 'Annual Total') %>%
  group_by(Agency) %>%
  filter(all(c("HR", "MB") %in% Mode)) %>%
  ungroup()%>%
  slice_head(n = 20)%>%
  select(-c(NTD.ID,UZA.Name, Agency.VOMS, Organization.Type, Mode.VOMS.Questionable, UACE.Code, Reporter.Type, Type.Of.Service,Primary.UZA.Area.Sq.Miles,  Time.Period, Time.Service.Begins, Time.Service.Ends))%>%
  select(where(~all(!is.na(.))))

Agencies <- Agencies[, c(names(Agencies)[1:7], "Unlinked.Passenger.Trips..UPT.", "Service.Area.Population")]

```

### Breakdown Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Read the dataset for revenue
breakdowns <- read.csv("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Breakdowns.csv")%>%
  filter(Type.of.Service == 'DO')%>%
  group_by(Agency) %>%
  filter(all(c("HR", "MB") %in% Mode)) %>%
  ungroup()%>%
  select(City, Mode,  Total.Mechanical.Failures)

```

### Maintenance Facilities Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
maintenance_facilities <- read_csv("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Maintenance.csv") 
maintenance_facilities <- maintenance_facilities %>%
  group_by(Agency) %>%
  filter(all(c("HR", "MB") %in% Mode)) %>%
  ungroup()%>%
  select(City, Mode, `Total Facilities`)%>%
  rename(Maintenance_Facilities = `Total Facilities`)
```

### Track and Roadway Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
track_road <- read_csv("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Track_Roadway.csv")%>%
  group_by(Agency) %>%
  filter(all(c("HR", "MB") %in% Mode)) %>%
  ungroup()%>%
  select(City, Mode, `Total Track Miles`, `Total Miles`)

track_road <- track_road %>%
  mutate(Total_Miles = case_when(
    Mode == "HR" ~ `Total Track Miles`,
    Mode == "MB" ~ `Total Miles`
  )) %>%
  select(-`Total Track Miles`, -`Total Miles`)
```

### Stations Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
stations <- read_excel("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Stations.xlsx")%>%
  filter(TOS == 'DO') %>%
  filter(Mode %in% c('HR', 'MB')) %>%
  group_by(`Agency Name`) %>%
  filter(all(c("HR", "MB") %in% Mode)) %>%
  ungroup()%>%
  select(-c(`NTD ID`, TOS, `Reporter Type`, `Group Plan Sponsor NTD ID`, `Group Plan Sponsor Name`, `Reporting Module`, Elevators, Escalators))%>%
  rename(Agency = `Agency Name`)%>%
   mutate(Agency = ifelse(Agency == "County of Miami-Dade", 
                         "County of Miami-Dade , dba: Transportation & Public Work", 
                         ifelse(Agency == "Los Angeles County Metropolitan Transportation Authority", 
                                "Los Angeles County Metropolitan Transportation Authority , dba: Metro", 
                                Agency)))

```

### Operating Hours Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
hours <- read_csv("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Hours.csv") %>%
  group_by(`Agency`) %>%
  filter(all(c("HR", "MB") %in% Mode)) %>%
  ungroup()%>%
  select(City, Mode, `Actual Vehicles/ Passenger Car Hours`, `Train Revenue Hours`,  `Average Passenger Trip Length (APTL)`, `Passengers per Vehicle Revenue Hour`)%>%
  mutate(Total_Hours = case_when(
    Mode == "HR" ~ `Actual Vehicles/ Passenger Car Hours` + `Train Revenue Hours`,
    Mode == "MB" ~ `Actual Vehicles/ Passenger Car Hours`,
    TRUE ~ NA_real_
  ))%>%
  select(-c(`Actual Vehicles/ Passenger Car Hours`, `Train Revenue Hours`))

```


### Capacity Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
capacity <- read_excel("/Users/helenalindsay/Documents/Spring_24/Capstone/Data/Capacity.xlsx")%>%
  filter(Modes %in% c('HR/DO', 'MB/DO')) %>%
  filter(`Vehicle Type` %in% c('Heavy Rail Passenger Car', 'Bus')) %>%
  group_by(`Agency Name`) %>%
  filter(all(c("HR/DO", "MB/DO") %in% Modes)) %>%
  ungroup()%>%
  mutate(Mode = gsub("/DO", "", Modes)) %>%
  select(-Modes) %>%
  rename(Agency = `Agency Name`)%>%
  select(Agency, Mode,  `Vehicle Length`, `Seating Capacity`, `Standing Capacity`)%>%
  group_by(Agency, Mode) %>%
  summarize(
    `Vehicle Length` = first(`Vehicle Length`),
    `Seating Capacity` = mean(`Seating Capacity`),
    `Standing Capacity` = mean(`Standing Capacity`)
  )%>%
   mutate(Agency = ifelse(Agency == "County of Miami-Dade", 
                         "County of Miami-Dade , dba: Transportation & Public Work", 
                         ifelse(Agency == "Los Angeles County Metropolitan Transportation Authority", 
                                "Los Angeles County Metropolitan Transportation Authority , dba: Metro", 
                                Agency)))

```



### Employees Data
```{r, message=FALSE, warning=FALSE, echo=FALSE}
employees <- read_csv("/Users/helenalindsay/Documents/Spring_24/Capstone/2022_NTD_Annual_Data_-_Employees__by_Mode_and_Employee_Type__20240717.csv") 
employees <- employees %>%
  filter(City %in% c("Atlanta", "Baltimore", "Boston", "Brooklyn", "Chicago", "Cleveland", "Los Angeles", "Miami", "Philadelphia", "Washington"))%>%
  filter(`Full or Part Time` == 'Full Time')%>%
  select(-contains("Questionable"))%>%
  filter(Mode %in% c('HR', 'MB'))%>%
  select(2, 11, ncol(.))


```

### TAM Performance
```{r, message=FALSE, warning=FALSE, echo=FALSE}
TAM <- read_csv("/Users/helenalindsay/Documents/Spring_24/Capstone/2022-TAM-Performance-Tool_0(1)/2022 Data-Table 1.csv") 

TAM <- TAM %>%
  filter(City %in% c("Atlanta", "Baltimore", "Boston", "Brooklyn", "Chicago", "Cleveland", "Los Angeles", "Miami", "Philadelphia", "Washington"))%>%
  select(-contains("Questionable"))%>%
  filter(Mode %in% c('HR', 'MB'))%>%
  filter(`Reporter Type` == 'Full Reporter')%>%
  group_by(City, Mode) %>%
  summarise(across(where(is.numeric), sum, na.rm = TRUE))%>%
  select(-contains("2021"))%>%
  select(1:8)


```

### Join
```{r, message=FALSE, warning=FALSE, echo=FALSE}
merged_data <- left_join(Agencies, breakdowns, by = c("City", "Mode"))%>%
  left_join(maintenance_facilities, by = c("City", "Mode"))%>%
  left_join(track_road, by = c("City", "Mode"))%>%
  left_join(stations, by = c("Agency", "Mode"))%>%
  left_join(hours, by = c("City", "Mode"))%>%
  left_join(capacity, by = c("Agency", "Mode"))%>%
  left_join(employees, by = c("City", "Mode"))%>%
  left_join(TAM, by = c("City", "Mode"))


names(merged_data)
#write_csv(merged_data, "/Users/helenalindsay/Documents/Spring_24/Capstone/Data/merged_data.csv")
```

### Join
```{r, message=FALSE, warning=FALSE, echo=FALSE}
# MARTA MB stations 8981

merged_data <- merged_data %>%
  mutate(`Total Stations` = ifelse(City == "Atlanta" & Mode == "MB", 8909, `Total Stations`), `Total_Miles`= ifelse(City == "Atlanta" & Mode == "MB", 1153, `Total_Miles`))%>%
 select(-c(`ADA Accessible Stations`, `Non-ADA Accessible Stations`))

merged_data <- merged_data %>%
  mutate(Service.Area.Sq.Miles = ifelse(City == "Baltimore", 2286, `Service.Area.Sq.Miles`))

merged_data <- merged_data %>%
  mutate(`Total_Miles`= ifelse(City == "Baltimore" & Mode == "HR", 51.76, `Total_Miles`))

merged_data <- merged_data %>%
  mutate(`Total Stations` = ifelse(City == "Baltimore" & Mode == "MB", 4016, `Total Stations`), `Total_Miles`= ifelse(City == "Baltimore" & Mode == "MB", 1094.5, `Total_Miles`))

merged_data <- merged_data %>%
  mutate(Service.Area.Sq.Miles = ifelse(City == "Boston", 3662.44, `Service.Area.Sq.Miles`), `Total Stations` = ifelse(City == "Boston" & Mode == "MB", 8919, `Total Stations`), `Total_Miles` = ifelse(City == "Boston" & Mode == "HR", 313.38, `Total_Miles`))

merged_data <- merged_data %>%
  mutate(Service.Area.Sq.Miles = ifelse(City == "Brooklyn", 383.5, `Service.Area.Sq.Miles`), `Total Stations` = ifelse(City == "Brooklyn" & Mode == "HR", 499, `Total Stations`), `Total_Miles`= ifelse(City == "Brooklyn" & Mode == "HR", 662, `Total_Miles`), `Total Stations` = ifelse(City == "Brooklyn" & Mode == "MB", 12398, `Total Stations`), `Total_Miles`= ifelse(City == "Brooklyn" & Mode == "MB", 1591.2, `Total_Miles`))

merged_data <- merged_data %>%
  mutate(`Total Stations` = ifelse(City == "Chicago" & Mode == "MB", 10704, `Total Stations`), `Total_Miles`= ifelse(City == "Chicago" & Mode == "HR", 360, `Total_Miles`), `Total_Miles`= ifelse(City == "Chicago" & Mode == "MB", 11461.44, `Total_Miles`))

merged_data <- merged_data %>%
  mutate(`Total Stations` = ifelse(City == "Cleveland" & Mode == "HR", 35, `Total Stations`), `Total_Miles`= ifelse(City == "Cleveland" & Mode == "HR", 74.5, `Total_Miles`), `Total Stations` = ifelse(City == "Cleveland" & Mode == "MB", 5473, `Total Stations`))


merged_data <- merged_data %>%
  mutate(Service.Area.Sq.Miles = ifelse(City == "Los Angeles", 3961.3, `Service.Area.Sq.Miles`),`Total Stations` = ifelse(City == "Los Angeles" & Mode == "MB", 12007, `Total Stations`), `Total_Miles`= ifelse(City == "Los Angeles" & Mode == "MB", 10045.2, `Total_Miles`))


merged_data <- merged_data %>%
  mutate(`Total_Miles`= ifelse(City == "Miami" & Mode == "HR", 112.19, `Total_Miles`),`Total Stations` = ifelse(City == "Miami" & Mode == "MB", 6376, `Total Stations`),`Total_Miles`= ifelse(City == "Miami" & Mode == "MB", 3867, `Total_Miles`), Service.Area.Sq.Miles = ifelse(City == "Miami", 428.31, `Service.Area.Sq.Miles`))


merged_data <- merged_data %>%
  mutate(`Total_Miles`= ifelse(City == "Philadelphia" & Mode == "HR", 305.1, `Total_Miles`),`Total Stations` = ifelse(City == "Philadelphia" & Mode == "HR", 156, `Total Stations`),`Total Stations` = ifelse(City == "Philadelphia" & Mode == "MB", 12659, `Total Stations`), , Service.Area.Sq.Miles = ifelse(City == "Philadelphia", 1234.27, `Service.Area.Sq.Miles`), `Total_Miles`= ifelse(City == "Philadelphia" & Mode == "MB", 1625.921, `Total_Miles`))


merged_data <- merged_data %>%
  mutate(`Total Stations` = ifelse(City == "Washington" & Mode == "MB", 9267, `Total Stations`),`Total_Miles`= ifelse(City == "Washington" & Mode == "MB", 4982.04, `Total_Miles`),`Total_Miles`= ifelse(City == "Washington" & Mode == "HR", 166.3, `Total_Miles`))



load("/Users/helenalindsay/Documents/Spring_24/avg_scores_df.RData")


DATA <- merged_data %>%
  left_join(avg_scores_df, by = c("City", "Mode"))

Scores <- read.csv("/Users/helenalindsay/Documents/Spring_24/GIS_Capstone/LITA_SCORES.csv")


# Merge new_data with DATA
DATA <- merge(DATA, Scores, by = c("City", "Mode"), all.x = TRUE)%>%
  select(-c(city_name, Mode.VOMS, Unlinked.Passenger.Trips..UPT.))

DATA$`%UnderThreshold` <- (DATA$`Units Under Performance Threshold (2022)`/DATA$`Total Units (2022)`)*100

DATA <- DATA%>%
  select(-c(`Units Under Performance Threshold (2022)`, `Total Units (2022)`))

# Display the updated dataset
kable(head(DATA)) 

save(DATA, file = "/Users/helenalindsay/Documents/Spring_24/DATA.RData")
```


